# Generated by Django 3.0.1 on 2019-12-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=30)),
                ('device_type', models.CharField(max_length=30)),
                ('register_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('u_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('u_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('attribute1', models.BooleanField()),
                ('attribute2', models.BooleanField()),
                ('attribute3', models.BooleanField()),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('devices', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientific_database_app.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='device_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientific_database_app.Student'),
        ),
    ]
