# Generated by Django 3.0.4 on 2020-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0012_auto_20200307_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
