# Generated by Django 3.0.4 on 2020-03-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0013_auto_20200307_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='Device Name', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='Device Type', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientific_database_app.Student', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateField(),
        ),
    ]
