# Generated by Django 3.0.4 on 2020-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0017_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateTimeField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_name',
            field=models.CharField(default='Measurement Name', max_length=30, verbose_name='Name'),
        ),
    ]
