# Generated by Django 3.0.4 on 2020-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0018_auto_20200308_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='person_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Type your Name here'),
        ),
        migrations.AlterField(
            model_name='device',
            name='register_date',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='choice1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=30, verbose_name='On-site?'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='choice2',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('malfunction', 'Malfunction')], default='Active', max_length=30, verbose_name='Condition before'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='choice3',
            field=models.CharField(choices=[('active', 'Active'), ('active_with_problems', 'Active with Problems'), ('inactive', 'Inactive')], default='Active', max_length=30, verbose_name='Condition after'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
