# Generated by Django 3.0.4 on 2020-04-29 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0021_maintenance_choice4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Timestamp'),
        ),
    ]
