# Generated by Django 3.0.4 on 2020-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0024_auto_20200429_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='person_name',
            field=models.CharField(default='', max_length=30, verbose_name='Type your Name here'),
        ),
    ]
