# Generated by Django 3.0.4 on 2020-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0027_auto_20200429_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='person_name',
            field=models.CharField(max_length=30),
        ),
    ]
