# Generated by Django 3.0.4 on 2020-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0028_auto_20200429_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='choice1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=30),
        ),
    ]
