# Generated by Django 3.0.4 on 2020-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0029_auto_20200429_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='choice1',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=30, verbose_name='On-site?'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(default=None, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='person_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Type your Name here'),
        ),
    ]
