# Generated by Django 3.0.4 on 2020-04-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0031_auto_20200429_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_description',
            field=models.TextField(default=None, verbose_name='Measurement Description'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Measurement Name'),
        ),
    ]
