# Generated by Django 3.0.4 on 2020-05-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0034_auto_20200504_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='associated_devices',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientific_database_app.Device'),
        ),
        migrations.AddField(
            model_name='networks',
            name='associated_devices',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientific_database_app.Device'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='networks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scientific_database_app.Networks'),
        ),
    ]
