# Generated by Django 3.0.6 on 2020-05-08 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientific_database_app', '0035_auto_20200504_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networks',
            name='associated_devices',
        ),
        migrations.AddField(
            model_name='device',
            name='associated_network',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientific_database_app.Networks'),
        ),
    ]
